project:
  type: website

website:
  title: "Welcome to my Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Bhupawsubedi
      - icon: Linkedin
        href: https://www.linkedin.com/in/bhupa-subedi-219312201/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

